/*
 * wgsl_sources.h - WGSL shader source strings embedded as C string literals
 *
 * In a production build, these would be auto-generated from the .wgsl files.
 * For now, we read the .wgsl files and embed them manually.
 */

#ifndef WGSL_SOURCES_H
#define WGSL_SOURCES_H

/* These are also referenced by webgpu_kernels.c for the element-wise ops */
const char *wgsl_elementwise =
    "struct Params {\n"
    "    n: u32,\n"
    "    _pad0: u32,\n"
    "    value: f32,\n"
    "    _pad1: f32,\n"
    "}\n"
    "@group(0) @binding(0) var<storage, read_write> data: array<f32>;\n"
    "@group(0) @binding(1) var<uniform> params: Params;\n"
    "@compute @workgroup_size(256)\n"
    "fn fill(@builtin(global_invocation_id) gid: vec3<u32>) {\n"
    "    let i = gid.x;\n"
    "    if (i >= params.n) { return; }\n"
    "    data[i] = params.value;\n"
    "}\n"
    "@compute @workgroup_size(256)\n"
    "fn scale(@builtin(global_invocation_id) gid: vec3<u32>) {\n"
    "    let i = gid.x;\n"
    "    if (i >= params.n) { return; }\n"
    "    data[i] = data[i] * params.value;\n"
    "}\n";

const char *wgsl_axpy =
    "struct Params {\n"
    "    n: u32,\n"
    "    _pad0: u32,\n"
    "    value: f32,\n"
    "    _pad1: f32,\n"
    "}\n"
    "@group(0) @binding(0) var<storage, read_write> data: array<f32>;\n"
    "@group(0) @binding(1) var<uniform> params: Params;\n"
    "@group(0) @binding(2) var<storage, read> x_data: array<f32>;\n"
    "@compute @workgroup_size(256)\n"
    "fn axpy(@builtin(global_invocation_id) gid: vec3<u32>) {\n"
    "    let i = gid.x;\n"
    "    if (i >= params.n) { return; }\n"
    "    data[i] = data[i] + params.value * x_data[i];\n"
    "}\n";

/* Grid sample forward */
static const char wgsl_grid_sample_fwd[] =
    "struct P { B: u32, C: u32, iD: u32, iH: u32, iW: u32, oD: u32, oH: u32, oW: u32, }\n"
    "@group(0) @binding(0) var<storage, read> input: array<f32>;\n"
    "@group(0) @binding(1) var<storage, read> grid: array<f32>;\n"
    "@group(0) @binding(2) var<storage, read_write> output: array<f32>;\n"
    "@group(0) @binding(3) var<uniform> p: P;\n"
    "fn unnorm(x: f32, s: u32) -> f32 { return (x + 1.0) * 0.5 * f32(s - 1u); }\n"
    "fn get_inp(b: u32, c: u32, d: i32, h: i32, w: i32) -> f32 {\n"
    "    if (d < 0 || d >= i32(p.iD) || h < 0 || h >= i32(p.iH) || w < 0 || w >= i32(p.iW)) { return 0.0; }\n"
    "    return input[((b * p.C + c) * p.iD + u32(d)) * p.iH * p.iW + u32(h) * p.iW + u32(w)];\n"
    "}\n"
    "@compute @workgroup_size(256)\n"
    "fn grid_sample_fwd(@builtin(global_invocation_id) gid: vec3<u32>) {\n"
    "    let idx = gid.x;\n"
    "    if (idx >= p.B * p.oD * p.oH * p.oW) { return; }\n"
    "    let w = idx % p.oW; var tmp = idx / p.oW;\n"
    "    let h = tmp % p.oH; tmp = tmp / p.oH;\n"
    "    let d = tmp % p.oD; let b = tmp / p.oD;\n"
    "    let gi = idx * 3u;\n"
    "    let ix = unnorm(grid[gi], p.iW); let iy = unnorm(grid[gi+1u], p.iH); let iz = unnorm(grid[gi+2u], p.iD);\n"
    "    let x0 = i32(floor(ix)); let y0 = i32(floor(iy)); let z0 = i32(floor(iz));\n"
    "    let fx = ix - f32(x0); let fy = iy - f32(y0); let fz = iz - f32(z0);\n"
    "    let os = p.oD * p.oH * p.oW;\n"
    "    var ob = (b * p.C * p.oD + d) * p.oH * p.oW + h * p.oW + w;\n"
    "    for (var c = 0u; c < p.C; c++) {\n"
    "        let v = (1.0-fx)*(1.0-fy)*(1.0-fz)*get_inp(b,c,z0,y0,x0)\n"
    "              + fx*(1.0-fy)*(1.0-fz)*get_inp(b,c,z0,y0,x0+1)\n"
    "              + (1.0-fx)*fy*(1.0-fz)*get_inp(b,c,z0,y0+1,x0)\n"
    "              + fx*fy*(1.0-fz)*get_inp(b,c,z0,y0+1,x0+1)\n"
    "              + (1.0-fx)*(1.0-fy)*fz*get_inp(b,c,z0+1,y0,x0)\n"
    "              + fx*(1.0-fy)*fz*get_inp(b,c,z0+1,y0,x0+1)\n"
    "              + (1.0-fx)*fy*fz*get_inp(b,c,z0+1,y0+1,x0)\n"
    "              + fx*fy*fz*get_inp(b,c,z0+1,y0+1,x0+1);\n"
    "        output[ob + c * os] = v;\n"
    "    }\n"
    "}\n";

/* Grid sample backward */
static const char wgsl_grid_sample_bwd[] =
    "struct P { B: u32, C: u32, iD: u32, iH: u32, iW: u32, oD: u32, oH: u32, oW: u32, }\n"
    "@group(0) @binding(0) var<storage, read> go: array<f32>;\n"
    "@group(0) @binding(1) var<storage, read> input: array<f32>;\n"
    "@group(0) @binding(2) var<storage, read> grid: array<f32>;\n"
    "@group(0) @binding(3) var<storage, read_write> gg: array<f32>;\n"
    "@group(0) @binding(4) var<uniform> p: P;\n"
    "fn unnorm(x: f32, s: u32) -> f32 { return (x + 1.0) * 0.5 * f32(s - 1u); }\n"
    "fn gi(b: u32, c: u32, d: i32, h: i32, w: i32) -> f32 {\n"
    "    if (d<0||d>=i32(p.iD)||h<0||h>=i32(p.iH)||w<0||w>=i32(p.iW)){return 0.0;}\n"
    "    return input[((b*p.C+c)*p.iD+u32(d))*p.iH*p.iW+u32(h)*p.iW+u32(w)];\n"
    "}\n"
    "@compute @workgroup_size(256)\n"
    "fn grid_sample_bwd(@builtin(global_invocation_id) gid: vec3<u32>) {\n"
    "    let idx = gid.x;\n"
    "    if (idx >= p.B*p.oD*p.oH*p.oW) { return; }\n"
    "    let w = idx%p.oW; var tmp = idx/p.oW;\n"
    "    let h = tmp%p.oH; tmp = tmp/p.oH;\n"
    "    let d = tmp%p.oD; let b = tmp/p.oD;\n"
    "    let gx = grid[idx*3u]; let gy = grid[idx*3u+1u]; let gz = grid[idx*3u+2u];\n"
    "    let ix = unnorm(gx,p.iW); let iy = unnorm(gy,p.iH); let iz = unnorm(gz,p.iD);\n"
    "    let x0=i32(floor(ix)); let y0=i32(floor(iy)); let z0=i32(floor(iz));\n"
    "    let fx=ix-f32(x0); let fy=iy-f32(y0); let fz=iz-f32(z0);\n"
    "    var dgx=0.0f; var dgy=0.0f; var dgz=0.0f;\n"
    "    for (var c=0u; c<p.C; c++) {\n"
    "        let goi = ((b*p.C+c)*p.oD+d)*p.oH*p.oW+h*p.oW+w;\n"
    "        let g = go[goi];\n"
    "        let dfx = -(1.0-fy)*(1.0-fz)*gi(b,c,z0,y0,x0)+(1.0-fy)*(1.0-fz)*gi(b,c,z0,y0,x0+1)\n"
    "                  -fy*(1.0-fz)*gi(b,c,z0,y0+1,x0)+fy*(1.0-fz)*gi(b,c,z0,y0+1,x0+1)\n"
    "                  -(1.0-fy)*fz*gi(b,c,z0+1,y0,x0)+(1.0-fy)*fz*gi(b,c,z0+1,y0,x0+1)\n"
    "                  -fy*fz*gi(b,c,z0+1,y0+1,x0)+fy*fz*gi(b,c,z0+1,y0+1,x0+1);\n"
    "        let dfy = -(1.0-fx)*(1.0-fz)*gi(b,c,z0,y0,x0)-fx*(1.0-fz)*gi(b,c,z0,y0,x0+1)\n"
    "                  +(1.0-fx)*(1.0-fz)*gi(b,c,z0,y0+1,x0)+fx*(1.0-fz)*gi(b,c,z0,y0+1,x0+1)\n"
    "                  -(1.0-fx)*fz*gi(b,c,z0+1,y0,x0)-fx*fz*gi(b,c,z0+1,y0,x0+1)\n"
    "                  +(1.0-fx)*fz*gi(b,c,z0+1,y0+1,x0)+fx*fz*gi(b,c,z0+1,y0+1,x0+1);\n"
    "        let dfz = -(1.0-fx)*(1.0-fy)*gi(b,c,z0,y0,x0)-fx*(1.0-fy)*gi(b,c,z0,y0,x0+1)\n"
    "                  -(1.0-fx)*fy*gi(b,c,z0,y0+1,x0)-fx*fy*gi(b,c,z0,y0+1,x0+1)\n"
    "                  +(1.0-fx)*(1.0-fy)*gi(b,c,z0+1,y0,x0)+fx*(1.0-fy)*gi(b,c,z0+1,y0,x0+1)\n"
    "                  +(1.0-fx)*fy*gi(b,c,z0+1,y0+1,x0)+fx*fy*gi(b,c,z0+1,y0+1,x0+1);\n"
    "        dgx+=g*dfx; dgy+=g*dfy; dgz+=g*dfz;\n"
    "    }\n"
    "    gg[idx*3u] = dgx * f32(p.iW-1u)*0.5;\n"
    "    gg[idx*3u+1u] = dgy * f32(p.iH-1u)*0.5;\n"
    "    gg[idx*3u+2u] = dgz * f32(p.iD-1u)*0.5;\n"
    "}\n";

/* Affine grid */
static const char wgsl_affine_grid[] =
    "struct P { B: u32, D: u32, H: u32, W: u32, }\n"
    "@group(0) @binding(0) var<storage, read> A: array<f32>;\n"
    "@group(0) @binding(1) var<storage, read_write> grid: array<f32>;\n"
    "@group(0) @binding(2) var<uniform> p: P;\n"
    "@compute @workgroup_size(256)\n"
    "fn affine_grid(@builtin(global_invocation_id) gid: vec3<u32>) {\n"
    "    let idx = gid.x;\n"
    "    if (idx >= p.B*p.D*p.H*p.W) { return; }\n"
    "    let w = idx%p.W; var tmp = idx/p.W;\n"
    "    let h = tmp%p.H; tmp=tmp/p.H;\n"
    "    let d = tmp%p.D; let b = tmp/p.D;\n"
    "    var nz: f32; var ny: f32; var nx: f32;\n"
    "    if (p.D>1u) { nz = 2.0*f32(d)/f32(p.D-1u)-1.0; } else { nz = 0.0; }\n"
    "    if (p.H>1u) { ny = 2.0*f32(h)/f32(p.H-1u)-1.0; } else { ny = 0.0; }\n"
    "    if (p.W>1u) { nx = 2.0*f32(w)/f32(p.W-1u)-1.0; } else { nx = 0.0; }\n"
    "    let a = b*12u;\n"
    "    grid[idx*3u] = A[a]*nx+A[a+1u]*ny+A[a+2u]*nz+A[a+3u];\n"
    "    grid[idx*3u+1u] = A[a+4u]*nx+A[a+5u]*ny+A[a+6u]*nz+A[a+7u];\n"
    "    grid[idx*3u+2u] = A[a+8u]*nx+A[a+9u]*ny+A[a+10u]*nz+A[a+11u];\n"
    "}\n";

/* Trilinear resize */
static const char wgsl_resize[] =
    "struct P { B:u32,C:u32,iD:u32,iH:u32,iW:u32,oD:u32,oH:u32,oW:u32,ac:u32,_p:u32, }\n"
    "@group(0) @binding(0) var<storage, read> inp: array<f32>;\n"
    "@group(0) @binding(1) var<storage, read_write> out: array<f32>;\n"
    "@group(0) @binding(2) var<uniform> p: P;\n"
    "@compute @workgroup_size(256)\n"
    "fn trilinear_resize(@builtin(global_invocation_id) gid: vec3<u32>) {\n"
    "    let idx = gid.x;\n"
    "    if (idx >= p.B*p.C*p.oD*p.oH*p.oW) { return; }\n"
    "    let ow=idx%p.oW; var tmp=idx/p.oW;\n"
    "    let oh=tmp%p.oH; tmp=tmp/p.oH;\n"
    "    let od=tmp%p.oD; tmp=tmp/p.oD;\n"
    "    let c=tmp%p.C; let b=tmp/p.C;\n"
    "    var sd:f32; var sh:f32; var sw:f32;\n"
    "    if (p.ac!=0u && p.oD>1u) { sd=f32(od)*f32(p.iD-1u)/f32(p.oD-1u); }\n"
    "    else { sd=(f32(od)+0.5)*f32(p.iD)/f32(p.oD)-0.5; }\n"
    "    if (p.ac!=0u && p.oH>1u) { sh=f32(oh)*f32(p.iH-1u)/f32(p.oH-1u); }\n"
    "    else { sh=(f32(oh)+0.5)*f32(p.iH)/f32(p.oH)-0.5; }\n"
    "    if (p.ac!=0u && p.oW>1u) { sw=f32(ow)*f32(p.iW-1u)/f32(p.oW-1u); }\n"
    "    else { sw=(f32(ow)+0.5)*f32(p.iW)/f32(p.oW)-0.5; }\n"
    "    var d0=i32(floor(sd)); var h0=i32(floor(sh)); var w0=i32(floor(sw));\n"
    "    var d1=d0+1; var h1=h0+1; var w1=w0+1;\n"
    "    var fd=sd-f32(d0); var fh=sh-f32(h0); var fw=sw-f32(w0);\n"
    "    if(d0<0){d0=0;fd=0.0;} if(d1>=i32(p.iD)){d1=i32(p.iD)-1;}\n"
    "    if(h0<0){h0=0;fh=0.0;} if(h1>=i32(p.iH)){h1=i32(p.iH)-1;}\n"
    "    if(w0<0){w0=0;fw=0.0;} if(w1>=i32(p.iW)){w1=i32(p.iW)-1;}\n"
    "    let base = (b*p.C+c)*p.iD*p.iH*p.iW;\n"
    "    let s = p.iH*p.iW;\n"
    "    let v = (1.0-fd)*(1.0-fh)*(1.0-fw)*inp[base+u32(d0)*s+u32(h0)*p.iW+u32(w0)]\n"
    "          + (1.0-fd)*(1.0-fh)*fw*inp[base+u32(d0)*s+u32(h0)*p.iW+u32(w1)]\n"
    "          + (1.0-fd)*fh*(1.0-fw)*inp[base+u32(d0)*s+u32(h1)*p.iW+u32(w0)]\n"
    "          + (1.0-fd)*fh*fw*inp[base+u32(d0)*s+u32(h1)*p.iW+u32(w1)]\n"
    "          + fd*(1.0-fh)*(1.0-fw)*inp[base+u32(d1)*s+u32(h0)*p.iW+u32(w0)]\n"
    "          + fd*(1.0-fh)*fw*inp[base+u32(d1)*s+u32(h0)*p.iW+u32(w1)]\n"
    "          + fd*fh*(1.0-fw)*inp[base+u32(d1)*s+u32(h1)*p.iW+u32(w0)]\n"
    "          + fd*fh*fw*inp[base+u32(d1)*s+u32(h1)*p.iW+u32(w1)];\n"
    "    out[idx] = v;\n"
    "}\n";

/* Adam step */
static const char wgsl_adam[] =
    "struct P { n:u32, step:u32, lr:f32, beta1:f32, beta2:f32, eps:f32, _p0:u32, _p1:u32, }\n"
    "@group(0) @binding(0) var<storage, read_write> param: array<f32>;\n"
    "@group(0) @binding(1) var<storage, read> grad: array<f32>;\n"
    "@group(0) @binding(2) var<storage, read_write> ea: array<f32>;\n"
    "@group(0) @binding(3) var<storage, read_write> eas: array<f32>;\n"
    "@group(0) @binding(4) var<uniform> p: P;\n"
    "@compute @workgroup_size(256)\n"
    "fn adam_step(@builtin(global_invocation_id) gid: vec3<u32>) {\n"
    "    let i = gid.x; if (i >= p.n) { return; }\n"
    "    let g = grad[i];\n"
    "    let m = p.beta1*ea[i]+(1.0-p.beta1)*g;\n"
    "    let v = p.beta2*eas[i]+(1.0-p.beta2)*g*g;\n"
    "    ea[i]=m; eas[i]=v;\n"
    "    let bc1=1.0-pow(p.beta1,f32(p.step));\n"
    "    let bc2=1.0-pow(p.beta2,f32(p.step));\n"
    "    param[i] = param[i] - (p.lr/bc1)*m/(sqrt(v/bc2)+p.eps);\n"
    "}\n";

/* CC loss: box filter + multiply entry points */
static const char wgsl_cc_loss[] =
    /* multiply */
    "struct MulP { n:u32, _p0:u32, _p1:u32, _p2:u32, }\n"
    "@group(0) @binding(0) var<storage, read> ma: array<f32>;\n"
    "@group(0) @binding(1) var<storage, read> mb: array<f32>;\n"
    "@group(0) @binding(2) var<storage, read_write> mc: array<f32>;\n"
    "@group(0) @binding(3) var<uniform> mp: MulP;\n"
    "@compute @workgroup_size(256)\n"
    "fn multiply(@builtin(global_invocation_id) gid: vec3<u32>) {\n"
    "    let i = gid.x; if (i >= mp.n) { return; }\n"
    "    mc[i] = ma[i] * mb[i];\n"
    "}\n"

    /* box filter — separate shader module needed due to different bindings,
     * but for simplicity we use a different pipeline name */
    ;

/* Box filter (separate source since different bindings from multiply) */
static const char wgsl_box_filter[] =
    "struct BoxP { D:u32, H:u32, W:u32, ks:u32, axis:u32, _p0:u32, _p1:u32, _p2:u32, }\n"
    "@group(0) @binding(0) var<storage, read> bi: array<f32>;\n"
    "@group(0) @binding(1) var<storage, read_write> bo: array<f32>;\n"
    "@group(0) @binding(2) var<uniform> bp: BoxP;\n"
    "@compute @workgroup_size(256)\n"
    "fn box_filter(@builtin(global_invocation_id) gid: vec3<u32>) {\n"
    "    let idx = gid.x;\n"
    "    if (idx >= bp.D*bp.H*bp.W) { return; }\n"
    "    let w = idx%bp.W; var tmp = idx/bp.W;\n"
    "    let h = tmp%bp.H; let d = tmp/bp.H;\n"
    "    let r = i32(bp.ks/2u); let sc = 1.0/f32(bp.ks);\n"
    "    var sum = 0.0f;\n"
    "    if (bp.axis==2u) {\n"
    "        for (var k=-r; k<=r; k++) {\n"
    "            let ww=i32(w)+k;\n"
    "            if (ww>=0 && ww<i32(bp.W)) { sum+=bi[d*bp.H*bp.W+h*bp.W+u32(ww)]; }\n"
    "        }\n"
    "    } else if (bp.axis==1u) {\n"
    "        for (var k=-r; k<=r; k++) {\n"
    "            let hh=i32(h)+k;\n"
    "            if (hh>=0 && hh<i32(bp.H)) { sum+=bi[d*bp.H*bp.W+u32(hh)*bp.W+w]; }\n"
    "        }\n"
    "    } else {\n"
    "        for (var k=-r; k<=r; k++) {\n"
    "            let dd=i32(d)+k;\n"
    "            if (dd>=0 && dd<i32(bp.D)) { sum+=bi[u32(dd)*bp.H*bp.W+h*bp.W+w]; }\n"
    "        }\n"
    "    }\n"
    "    bo[idx] = sum*sc;\n"
    "}\n";

#endif /* WGSL_SOURCES_H */
