#!/usr/bin/env python3
"""Generate embedded_shaders.c from backend/webgpu/shaders/*.wgsl.

WASM has no filesystem to read the shaders from, and natively the disk path is
resolved against the working directory, so running from anywhere but the repo
root produced 'entry point not found' validation errors. Embedding removes both.
"""
import sys, pathlib

src_dir, out = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
files = sorted(src_dir.glob("*.wgsl"))

def literal(text):
    esc = text.replace("\\", "\\\\").replace('"', '\\"')
    return "\n".join('    "%s\\n"' % l for l in esc.split("\n"))

parts = ['/* Generated by scripts/embed_shaders.py. Do not edit. */',
         '#include "embedded_shaders.h"', '']
for i, f in enumerate(files):
    parts += ['static const char s%d[] =' % i, literal(f.read_text()) + ';', '']
parts += ['static const shader_entry_t table[] = {']
parts += ['    { "%s", s%d },' % (f.name, i) for i, f in enumerate(files)]
parts += ['};', '',
          'const shader_entry_t *embedded_shader_table(int *count) {',
          '    *count = (int)(sizeof(table) / sizeof(table[0]));',
          '    return table;',
          '}']
out.write_text("\n".join(parts) + "\n")
print("embed_shaders: %d shaders -> %s" % (len(files), out))
